sudo: false
dist: xenial
language: node_js
node_js: 8
cache:
  directories:
    - $HOME/.npm
addons:
  chrome: stable
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run build
  - npm run lint
  - npm run bundlesize
  - npm run test:ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run build:prerender-ghpages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/browser
  github_token: $PUSH_TOKEN
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change
